"""Add user_id to briefings

Revision ID: 1cfd55f84377
Revises: 464e14afe3ce
Create Date: 2026-09-01 22:11:31.824511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cfd55f84377'
down_revision: Union[str, Sequence[str], None] = '464e14afe3ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('briefings', sa.Column('user_id', sa.Integer(), nullable=True))

    op.execute("UPDATE briefings SET user_id = 1 WHERE user_id IS NULL")
    op.alter_column('briefings', 'user_id', nullable=False)

    op.create_index(op.f('ix_briefings_user_id'), 'briefings', ['user_id'], unique=False)
    op.create_foreign_key(None, 'briefings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'briefings', type_='foreignkey')
    op.drop_index(op.f('ix_briefings_user_id'), table_name='briefings')
    op.drop_column('briefings', 'user_id')
    # ### end Alembic commands ###
