"""Create briefings table

Revision ID: 3a965ac35d9a
Revises: 
Create Date: 2026-08-01 10:38:28.757011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a965ac35d9a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('briefings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_company', sa.String(), nullable=False),
    sa.Column('competitor_name', sa.String(), nullable=False),
    sa.Column('competitor_url', sa.String(), nullable=False),
    sa.Column('product_updates', sa.Text(), nullable=True),
    sa.Column('hiring_signals', sa.Text(), nullable=True),
    sa.Column('pricing_changes', sa.Text(), nullable=True),
    sa.Column('tech_stack_changes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_briefings_competitor_name'), 'briefings', ['competitor_name'], unique=False)
    op.create_index(op.f('ix_briefings_id'), 'briefings', ['id'], unique=False)
    op.create_index(op.f('ix_briefings_user_company'), 'briefings', ['user_company'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_briefings_user_company'), table_name='briefings')
    op.drop_index(op.f('ix_briefings_id'), table_name='briefings')
    op.drop_index(op.f('ix_briefings_competitor_name'), table_name='briefings')
    op.drop_table('briefings')
    # ### end Alembic commands ###
