"""Change competitor_url to competitor_urls array

Revision ID: eb140c71f637
Revises: 3a965ac35d9a
Create Date: 2026-08-08 07:23:38.790489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb140c71f637'
down_revision: Union[str, Sequence[str], None] = '3a965ac35d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('briefings', sa.Column('competitor_urls', postgresql.ARRAY(sa.String()), nullable=False))
    op.drop_column('briefings', 'competitor_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('briefings', sa.Column('competitor_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('briefings', 'competitor_urls')
    # ### end Alembic commands ###
