"""Add tracked_competitors table

Revision ID: fd3edcc8d676
Revises: 1cfd55f84377
Create Date: 2026-09-05 22:29:46.417099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd3edcc8d676'
down_revision: Union[str, Sequence[str], None] = '1cfd55f84377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_company', sa.String(), nullable=False),
    sa.Column('competitor_name', sa.String(), nullable=False),
    sa.Column('competitor_urls', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'competitor_name', name='uq_user_competitor')
    )
    op.create_index(op.f('ix_tracked_competitors_competitor_name'), 'tracked_competitors', ['competitor_name'], unique=False)
    op.create_index(op.f('ix_tracked_competitors_id'), 'tracked_competitors', ['id'], unique=False)
    op.create_index(op.f('ix_tracked_competitors_user_id'), 'tracked_competitors', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracked_competitors_user_id'), table_name='tracked_competitors')
    op.drop_index(op.f('ix_tracked_competitors_id'), table_name='tracked_competitors')
    op.drop_index(op.f('ix_tracked_competitors_competitor_name'), table_name='tracked_competitors')
    op.drop_table('tracked_competitors')
    # ### end Alembic commands ###
